### PR TITLE
README file

### PR DESCRIPTION
**Pull request by TiaanPeens**
This includes the problems experienced when trying to run Evert.
I think there is still a lot to add to this file but for now it will help to start Evert.

### CODE REVIEW

**Comment by NeillHerbst** [comment]
Should the first address you visit be not be `localhost:5000` instead of `localhost:5000/plugins`?

**Comment by TiaanPeens** [comment]
Yes you're correct. That was an error on my part.

**Comment by TiaanPeens** [comment]
I saw that all the packages I recommended to pip install is already included the `requirements.txt`. I'm guessing that I should change that part to `pip install -r requirements.txt` ?

**Comment by NeillHerbst** [comment]
Yes and no, I managed the project dependencies using a conda environment file. It is the environment.yml file. That has the latest dependencies. It might however be a good idea to update the requirements.txt file since not everyone uses Anaconda

**Comment by alchemyst** [comment]
@NeillHerbst This pull request currently contains

* Changes to .travis.yml to get the tests to run on travis (mostly just figuring out that conda doesn't actually obey the `python=` argument when installing environments.
* The start of Sphinx support for eventual inclusion on ReadTheDocs
* Expanded README.

I think most of this is OK and we should merge this.

**Review by NeillHerbst — COMMENTED** [review]
@alchemyst  and @TiaanPeens everything looks fine. My only concern is the removal of specific package versions in the `requirements.txt` file. I understand that we would want the latest versions but it could lead to some unexpected issues in the future should someone else try to install it at a later stage.

**Comment by alchemyst** [comment]
@TiaanPeens I agree. It may be useful to update the requirement versions to the current known working versions instead of removing the versions completely, or perhaps specify > version instead if we know a particular package gives problems at particular versions?

**Comment by TiaanPeens** [comment]
I updated the requirements.txt file to contain the working versions that is currently being used in Evert.

**Pull request merged**
